#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-globalid
Version  : 0.3.7
Release  : 6
URL      : https://rubygems.org/downloads/globalid-0.3.7.gem
Source0  : https://rubygems.org/downloads/globalid-0.3.7.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-activesupport
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc

%description
# Global ID - Reference models by URI
A Global ID is an app wide URI that uniquely identifies a model instance:

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n globalid-0.3.7
gem spec %{SOURCE0} -l --ruby > rubygem-globalid.gemspec

%build
export LANG=C
gem build rubygem-globalid.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
globalid-0.3.7.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/globalid-0.3.7.gem
/usr/lib64/ruby/gems/2.3.0/gems/globalid-0.3.7/MIT-LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/globalid-0.3.7/README.md
/usr/lib64/ruby/gems/2.3.0/gems/globalid-0.3.7/lib/global_id.rb
/usr/lib64/ruby/gems/2.3.0/gems/globalid-0.3.7/lib/global_id/global_id.rb
/usr/lib64/ruby/gems/2.3.0/gems/globalid-0.3.7/lib/global_id/identification.rb
/usr/lib64/ruby/gems/2.3.0/gems/globalid-0.3.7/lib/global_id/locator.rb
/usr/lib64/ruby/gems/2.3.0/gems/globalid-0.3.7/lib/global_id/railtie.rb
/usr/lib64/ruby/gems/2.3.0/gems/globalid-0.3.7/lib/global_id/signed_global_id.rb
/usr/lib64/ruby/gems/2.3.0/gems/globalid-0.3.7/lib/global_id/uri/gid.rb
/usr/lib64/ruby/gems/2.3.0/gems/globalid-0.3.7/lib/globalid.rb
/usr/lib64/ruby/gems/2.3.0/specifications/globalid-0.3.7.gemspec
